# Generated by Django 3.2 on 2021-04-26 16:38

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('ID_Songs', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Adoracao', 'Adoracao'), ('Santa Ceia', 'Santa Ceia'), ('Missoes', 'Missoes')], max_length=100)),
                ('singer', models.CharField(help_text='Cantor', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('lyrics', models.CharField(help_text='Letra da musica', max_length=2000)),
                ('composers', models.CharField(help_text='Compositores/Autores', max_length=200)),
                ('image', models.ImageField(upload_to='img/%y')),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
