# Generated by Django 3.2 on 2021-05-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_songs_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='music',
            field=models.FileField(upload_to='music/%y'),
        ),
    ]
