# Generated by Django 3.2 on 2021-05-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_songs_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='lyrics',
            field=models.TextField(help_text='Letra da musica', max_length=2000),
        ),
    ]
